import { Router, Request, Response, NextFunction } from "express";
import multer from "multer";
import cloudinary from "../../config/cloudinary";
import { requireAuth, requireHubAdmin, requireRole, optionalAuth } from "../../middleware/auth";
import { ApiError } from "../../middleware/errorHandler";
import { RequestWithUser } from "../../types";
import Student from "../../models/user.model";
import { InnovationCategory, DevelopmentStage, Idea, Feedback, Project, ProjectDiscussion, ProjectFile, MentorProfile, MentorRequest, MentorshipSession, Showcase, Notification, ReviewAssignment } from "../../models/innovation.model";
import { notify } from "../../services/innovation.service";
import { generateSignedDownloadUrl } from "../../services/cloudinary.service";

const router = Router();
const auth = requireAuth;
const actor = (req: Request) => (req as RequestWithUser).user;
const id = (req: Request) => req.params.id;
const asyncRoute = (fn: (req: Request, res: Response) => Promise<unknown>) => (req: Request, res: Response, next: NextFunction) => { fn(req, res).catch(next); };
const admin = [auth, requireHubAdmin];
const parse = (value: unknown, fallback: unknown[] = []) => Array.isArray(value) ? value : (typeof value === "string" ? value.split(",").map(v => v.trim()).filter(Boolean) : fallback);
const isAdmin = (user: RequestWithUser["user"]) => ["system_admin", "innovation_hub_admin"].includes(user.role);

const assignedIdeaIds = async (userId: string) => ReviewAssignment.find({ mentor: userId, status: { $in: ["pending", "accepted", "completed"] }, idea: { $ne: null } }).distinct("idea");
const assignedProjectIds = async (userId: string) => ReviewAssignment.find({ mentor: userId, status: { $in: ["pending", "accepted", "completed"] }, project: { $ne: null } }).distinct("project");
const ideaFilterFor = async (user: RequestWithUser["user"], includeModeration = false) => {
  if (isAdmin(user) && includeModeration) return {};
  const assigned = await assignedIdeaIds(user.id);
  return { $or: [
    { visibility: "public" },
    { owner: user.id },
    { teamMembers: { $elemMatch: { user: user.id, accepted: { $ne: false } } } },
    { _id: { $in: assigned } },
  ] };
};

const canAccessIdea = async (idea: any, user: RequestWithUser["user"]) => {
  if (isAdmin(user)) return true;
  if (idea.visibility === "public") return true;
  if (String(idea.owner) === user.id) return true;
  if (idea.teamMembers?.some((member: any) => String(member.user) === user.id && member.accepted !== false)) return true;
  return Boolean(await ReviewAssignment.exists({ idea: idea._id, mentor: user.id, status: { $in: ["pending", "accepted", "completed"] } }));
};
const canReviewIdea = async (idea: any, user: RequestWithUser["user"]) => isAdmin(user) || (idea.visibility === "public" && ["submitted", "under_review", "resubmitted"].includes(idea.status)) || Boolean(await ReviewAssignment.exists({ idea: idea._id, mentor: user.id, status: { $in: ["pending", "accepted"] } }));

// Classifications are public to support configurable forms; mutation is admin-only.
router.get("/categories-and-stages", asyncRoute(async (_req, res) => res.json({ success: true, data: { categories: await InnovationCategory.find({ active: true }).sort({ order: 1, name: 1 }), stages: await DevelopmentStage.find({ active: true }).sort({ order: 1, name: 1 }) } })));
router.post("/categories-and-stages/:type", ...admin, asyncRoute(async (req, res) => { const Model = req.params.type === "categories" ? InnovationCategory : req.params.type === "stages" ? DevelopmentStage : null; if (!Model) throw new ApiError(404, "Unknown category or stage"); const name = String(req.body.name || "").trim(); if (!name) throw new ApiError(400, "Name is required"); res.status(201).json({ success: true, data: await Model.create({ name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-") }) }); }));
router.patch("/categories-and-stages/:type/:id", ...admin, asyncRoute(async (req, res) => { const Model = req.params.type === "categories" ? InnovationCategory : req.params.type === "stages" ? DevelopmentStage : null; if (!Model) throw new ApiError(404, "Unknown category or stage"); const result = await Model.findByIdAndUpdate(req.params.id, { $set: req.body }, { new: true, runValidators: true }); if (!result) throw new ApiError(404, "Category or stage not found"); res.json({ success: true, data: result }); }));

router.get("/ideas", optionalAuth, asyncRoute(async (req, res) => { const q: Record<string, unknown> = {}; const u = (req as Partial<RequestWithUser>).user; if (u) Object.assign(q, await ideaFilterFor(u, req.query.moderation === "true")); else Object.assign(q, { visibility: "public" }); if (req.query.owner === "me" && u) q.owner = u.id; if (req.query.status && u && (isAdmin(u) || req.query.moderation !== "true")) q.status = req.query.status; if (req.query.visibility && req.query.visibility !== "all" && u && isAdmin(u)) q.visibility = req.query.visibility; if (req.query.category) q.category = req.query.category; if (req.query.stage) q.stage = req.query.stage; if (req.query.q) q.$text = { $search: String(req.query.q) }; const data = await Idea.find(q).populate("category stage owner teamMembers.user", "name surname email name slug").sort({ updatedAt: -1 }).limit(Math.min(Number(req.query.limit) || 50, 100)); res.json({ success: true, data }); }));
router.post("/ideas", auth, asyncRoute(async (req, res) => { const u = actor(req); const data = { ...req.body, owner: u.id, beneficiaries: parse(req.body.beneficiaries), teamMembers: parse(req.body.teamMembers) }; const idea = await Idea.create(data); res.status(201).json({ success: true, data: idea }); }));
router.get("/ideas/:id", optionalAuth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)).populate("category stage owner teamMembers.user"); if (!idea) throw new ApiError(404, "Idea not found"); const u = (req as Partial<RequestWithUser>).user; if (!u || !(await canAccessIdea(idea, u))) throw new ApiError(403, "Idea access denied"); res.json({ success: true, data: idea }); }));
router.patch("/ideas/:id", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea) throw new ApiError(404, "Idea not found"); const u = actor(req); if (String(idea.owner) !== u.id && !["system_admin", "innovation_hub_admin"].includes(u.role)) throw new ApiError(403, "Only the owner or admin can update this idea"); Object.assign(idea, req.body); await idea.save(); res.json({ success: true, data: idea }); }));
router.post("/ideas/:id/submit", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea || String(idea.owner) !== actor(req).id) throw new ApiError(404, "Idea not found"); idea.status = idea.status === "feedback_provided" ? "resubmitted" : "submitted"; await idea.save(); res.json({ success: true, data: idea }); }));
router.post("/ideas/:id/review", ...[auth, requireRole(["mentor", "system_admin", "innovation_hub_admin"])], asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea) throw new ApiError(404, "Idea not found"); const u = actor(req); if (!(await canReviewIdea(idea, u))) throw new ApiError(403, "This idea is not assigned to you for review"); const nextStatus = String(req.body.status); if (!["under_review", "feedback_provided", "approved", "rejected", "incubation", "archived"].includes(nextStatus)) throw new ApiError(400, "Invalid review status"); idea.reviewHistory.push({ reviewer: u.id as any, fromStatus: idea.status, toStatus: nextStatus, note: req.body.note, at: new Date() } as any); idea.status = nextStatus as any; await idea.save(); await ReviewAssignment.updateMany({ idea: idea._id, mentor: u.id }, { $set: { status: "completed", respondedAt: new Date() } }); if (["feedback_provided", "rejected", "approved"].includes(nextStatus)) await notify(String(idea.owner), "Idea review update", `Your idea is now ${nextStatus}.`); res.json({ success: true, data: idea }); }));
router.get("/ideas/:id/feedback", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea || !(await canAccessIdea(idea, actor(req)))) throw new ApiError(403, "Idea access denied"); res.json({ success: true, data: await Feedback.find({ idea: id(req) }).sort({ createdAt: 1 }).populate("author", "name surname") }); }));
router.post("/ideas/:id/feedback", ...[auth, requireRole(["mentor", "system_admin", "innovation_hub_admin"])], asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea || !(await canReviewIdea(idea, actor(req)))) throw new ApiError(403, "This idea is not assigned to you for review"); const feedback = await Feedback.create({ ...req.body, author: actor(req).id, idea: id(req), parent: req.body.parent || null, strengths: parse(req.body.strengths), opportunities: parse(req.body.opportunities), developmentAreas: parse(req.body.developmentAreas), questions: parse(req.body.questions), recommendations: parse(req.body.recommendations), supportRequired: parse(req.body.supportRequired) }); await Idea.findByIdAndUpdate(id(req), { $push: { feedback: feedback._id }, $set: { status: "feedback_provided" } }); await notify(String(idea.owner), "New idea feedback", "A mentor or administrator provided feedback on your idea."); res.status(201).json({ success: true, data: feedback }); }));

router.post("/ideas/:id/invitations", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea) throw new ApiError(404, "Idea not found"); const u = actor(req); if (String(idea.owner) !== u.id && !["system_admin", "innovation_hub_admin"].includes(u.role)) throw new ApiError(403, "Only the idea owner can invite members"); const target = await Student.findOne({ email: String(req.body.email || "").trim().toLowerCase(), isActive: true }); if (!target) throw new ApiError(404, "User not found with that email"); if (String(target._id) === u.id || idea.teamMembers?.some((m: any) => String(m.user) === String(target._id))) throw new ApiError(409, "User is already on this idea"); idea.teamMembers = idea.teamMembers || []; idea.teamMembers.push({ user: target._id, role: req.body.role || "viewer", accepted: false } as any); await idea.save(); await notify(String(target._id), "Idea invitation", `You were invited to collaborate on ${idea.title}.`, `/innovation/ideas/${idea._id}`); res.status(201).json({ success: true, data: idea }); }));
router.post("/ideas/:id/invitations/respond", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea) throw new ApiError(404, "Idea not found"); const member: any = idea.teamMembers?.find((m: any) => String(m.user) === actor(req).id && m.accepted === false); if (!member) throw new ApiError(404, "Invitation not found"); if (req.body.accepted) member.accepted = true; else idea.teamMembers = idea.teamMembers.filter((m: any) => m !== member); await idea.save(); res.json({ success: true, data: idea }); }));

router.get("/review-assignments", auth, asyncRoute(async (req, res) => { const u = actor(req); const filter = isAdmin(u) && req.query.all === "true" ? {} : { mentor: u.id }; const assignments = await ReviewAssignment.find(filter).populate("idea project mentor requestedBy", "title name email").sort({ createdAt: -1 }).limit(100); res.json({ success: true, data: assignments }); }));
router.post("/ideas/:id/review-assignments", ...admin, asyncRoute(async (req, res) => { const idea = await Idea.findById(id(req)); if (!idea) throw new ApiError(404, "Idea not found"); const mentor = await MentorProfile.findOne({ _id: req.body.mentorId, approved: true }); if (!mentor) throw new ApiError(404, "Approved mentor not found"); const assignment = await ReviewAssignment.findOneAndUpdate({ idea: idea._id, mentor: mentor.user }, { idea: idea._id, mentor: mentor.user, requestedBy: actor(req).id, note: req.body.note, status: "pending" }, { upsert: true, new: true, setDefaultsOnInsert: true }); await notify(String(mentor.user), "Idea review requested", `You have been asked to review ${idea.title}.`, `/innovation/ideas/${idea._id}`); res.status(201).json({ success: true, data: assignment }); }));
router.post("/projects/:id/review-assignments", ...admin, asyncRoute(async (req, res) => { const project = await Project.findById(id(req)); if (!project) throw new ApiError(404, "Project not found"); const mentor = await MentorProfile.findOne({ _id: req.body.mentorId, approved: true }); if (!mentor) throw new ApiError(404, "Approved mentor not found"); const assignment = await ReviewAssignment.findOneAndUpdate({ project: project._id, mentor: mentor.user }, { project: project._id, mentor: mentor.user, requestedBy: actor(req).id, note: req.body.note, status: "pending" }, { upsert: true, new: true, setDefaultsOnInsert: true }); await notify(String(mentor.user), "Project review requested", `You have been asked to review ${project.name}.`, `/innovation/projects/${project._id}`); res.status(201).json({ success: true, data: assignment }); }));
router.patch("/review-assignments/:id", auth, asyncRoute(async (req, res) => { const assignment: any = await ReviewAssignment.findById(id(req)); if (!assignment) throw new ApiError(404, "Review assignment not found"); const u = actor(req); if (!isAdmin(u) && String(assignment.mentor) !== u.id) throw new ApiError(403, "Assignment access denied"); const status = String(req.body.status); if (!["accepted", "declined", "cancelled"].includes(status)) throw new ApiError(400, "Invalid assignment status"); assignment.status = status; assignment.respondedAt = new Date(); await assignment.save(); if (assignment.idea) await notify(String((await Idea.findById(assignment.idea))?.owner), "Review assignment update", `A mentor has ${status} your review request.`); res.json({ success: true, data: assignment }); }));

router.get("/projects", auth, asyncRoute(async (req, res) => { const u = actor(req); const assigned = await assignedProjectIds(u.id); const filter = isAdmin(u) && req.query.all === "true" ? {} : { $or: [{ visibility: "public" }, { owner: u.id }, { "team.user": u.id }, { _id: { $in: assigned } }] }; const data = await Project.find(filter).populate("owner team.user", "name surname email").sort({ updatedAt: -1 }).limit(100); res.json({ success: true, data }); }));
router.post("/projects", auth, asyncRoute(async (req, res) => { const u = actor(req); const project = await Project.create({ ...req.body, owner: u.id, tags: parse(req.body.tags), team: [{ user: u.id, role: "owner", accepted: true }] }); res.status(201).json({ success: true, data: project }); }));
const projectAccess = async (req: Request) => { const p = await Project.findById(id(req)); if (!p) throw new ApiError(404, "Project not found"); const u = actor(req); const member = p.team.some((m: any) => String(m.user) === u.id && m.accepted); const assigned = await ReviewAssignment.exists({ project: p._id, mentor: u.id, status: { $in: ["pending", "accepted", "completed"] } }); if (!isAdmin(u) && p.visibility !== "public" && !member && String(p.owner) !== u.id && !assigned) throw new ApiError(403, "Project access denied"); return p; };
router.get("/projects/:id", auth, asyncRoute(async (req, res) => res.json({ success: true, data: await projectAccess(req) })));
router.post("/projects/:id/invitations", auth, asyncRoute(async (req, res) => { const p = await projectAccess(req); if (String(p.owner) !== actor(req).id && !["system_admin", "innovation_hub_admin"].includes(actor(req).role)) throw new ApiError(403, "Only the project owner can invite members"); const target = await Student.findOne({ email: String(req.body.email || "").trim().toLowerCase(), isActive: true }); if (!target) throw new ApiError(404, "User not found with that email"); if (String(target._id) === actor(req).id || p.team.some((m: any) => String(m.user) === String(target._id))) throw new ApiError(409, "User is already on this project"); if (p.collaborationRequired && !target.collaborationOptIn) throw new ApiError(409, "This user has opted out of collaboration"); p.team.push({ user: target._id, role: req.body.role || "viewer", accepted: false } as any); await p.save(); await notify(String(target._id), "Project invitation", `You were invited to join ${p.name}.`, `/innovation/projects/${p._id}`); res.status(201).json({ success: true, data: p }); }));
router.get("/invitations", auth, asyncRoute(async (req, res) => { const projects = await Project.find({ "team.user": actor(req).id, "team.accepted": false }).populate("owner team.user", "name surname email"); const invitations = projects.flatMap((p: any) => p.team.filter((m: any) => String(m.user?._id || m.user) === actor(req).id && !m.accepted).map((m: any) => ({ project: p, role: m.role, invitedAt: m.invitedAt }))); res.json({ success: true, data: invitations }); }));
router.post("/projects/:id/invitations/respond", auth, asyncRoute(async (req, res) => { const p = await Project.findById(id(req)); if (!p) throw new ApiError(404, "Project not found"); const member: any = p.team.find((m: any) => String(m.user) === actor(req).id && !m.accepted); if (!member) throw new ApiError(404, "Invitation not found"); if (req.body.accepted) member.accepted = true; else p.team = p.team.filter((m: any) => m !== member); await p.save(); res.json({ success: true, data: p }); }));
router.patch("/projects/:id/members/:userId", auth, asyncRoute(async (req, res) => { const p = await projectAccess(req); if (String(p.owner) !== actor(req).id && !["system_admin", "innovation_hub_admin"].includes(actor(req).role)) throw new ApiError(403, "Only the project owner can assign roles"); const member: any = p.team.find((m: any) => String(m.user) === req.params.userId); if (!member) throw new ApiError(404, "Project member not found"); const roles = ["co_owner", "researcher", "developer", "designer", "business", "advisor", "viewer"]; if (!roles.includes(req.body.role)) throw new ApiError(400, "Invalid project role"); member.role = req.body.role; await p.save(); await notify(req.params.userId, "Project role updated", `Your role on ${p.name} is now ${req.body.role}.`); res.json({ success: true, data: p }); }));
router.get("/projects/:id/discussions", auth, asyncRoute(async (req, res) => { await projectAccess(req); res.json({ success: true, data: await ProjectDiscussion.find({ project: id(req) }).sort({ createdAt: 1 }).populate("author", "name surname") }); }));
router.post("/projects/:id/discussions", auth, asyncRoute(async (req, res) => { await projectAccess(req); const d = await ProjectDiscussion.create({ project: id(req), author: actor(req).id, parent: req.body.parent || null, message: req.body.message }); res.status(201).json({ success: true, data: d }); }));

router.get("/collaborators", auth, asyncRoute(async (req, res) => { const q: Record<string, unknown> = { collaborationOptIn: true, isActive: true }; for (const field of ["skills", "interests", "faculty", "department"]) if (req.query[field]) q[field] = field === "skills" || field === "interests" ? { $in: parse(req.query[field]) } : req.query[field]; const users = await Student.find(q).select("name surname email faculty department skills interests profilePictureUrl").limit(100); res.json({ success: true, data: users }); }));

router.get("/mentors", optionalAuth, asyncRoute(async (req, res) => { const u = (req as Partial<RequestWithUser>).user; const filter: any = { approved: true, ...(req.query.expertise ? { expertise: { $in: parse(req.query.expertise) } } : {}) }; if (u && ["system_admin", "innovation_hub_admin"].includes(u.role) && req.query.includePending === "true") delete filter.approved; res.json({ success: true, data: await MentorProfile.find(filter).populate("user", "name surname email faculty department") }); }));
router.post("/mentors/profile", auth, requireRole(["mentor"]), asyncRoute(async (req, res) => { const profile = await MentorProfile.findOneAndUpdate({ user: actor(req).id }, { ...req.body, user: actor(req).id, approved: false, expertise: parse(req.body.expertise) }, { upsert: true, new: true }); res.status(201).json({ success: true, data: profile }); }));
router.patch("/mentors/:id/approval", ...admin, asyncRoute(async (req, res) => { const p = await MentorProfile.findByIdAndUpdate(id(req), { approved: Boolean(req.body.approved), approvedBy: actor(req).id, approvedAt: new Date() }, { new: true }); if (!p) throw new ApiError(404, "Mentor profile not found"); res.json({ success: true, data: p }); }));
router.post("/mentors/:id/requests", auth, asyncRoute(async (req, res) => { const mentor = await MentorProfile.findOne({ _id: id(req), approved: true }); if (!mentor) throw new ApiError(404, "Mentor not found"); const request = await MentorRequest.create({ mentor: mentor.user, requester: actor(req).id, message: req.body.message, history: [{ status: "pending", by: actor(req).id }] }); await notify(String(mentor.user), "Mentorship request", "You have a new mentorship request."); res.status(201).json({ success: true, data: request }); }));
router.patch("/mentor-requests/:id", auth, asyncRoute(async (req, res) => { const r: any = await MentorRequest.findById(id(req)); if (!r || (![String(r.mentor), String(r.requester)].includes(actor(req).id))) throw new ApiError(404, "Request not found"); r.status = req.body.status; r.history.push({ status: r.status, by: actor(req).id, note: req.body.note }); await r.save(); if (r.status === "accepted") await MentorshipSession.create({ mentor: r.mentor, mentee: r.requester, request: r._id }); res.json({ success: true, data: r }); }));
router.post("/mentor-requests/:id/replies", auth, asyncRoute(async (req, res) => { const r: any = await MentorRequest.findByIdAndUpdate(id(req), { $push: { replies: { author: actor(req).id, message: req.body.message } } }, { new: true }); if (!r) throw new ApiError(404, "Request not found"); res.json({ success: true, data: r }); }));
router.get("/mentorship-sessions", auth, asyncRoute(async (req, res) => res.json({ success: true, data: await MentorshipSession.find({ $or: [{ mentor: actor(req).id }, { mentee: actor(req).id }] }).populate("mentor mentee", "name surname") })));
router.post("/mentorship-sessions/:id/messages", auth, asyncRoute(async (req, res) => { const s: any = await MentorshipSession.findById(id(req)); if (!s || ![String(s.mentor), String(s.mentee)].includes(actor(req).id)) throw new ApiError(404, "Session not found"); s.messages.push({ author: actor(req).id, message: req.body.message }); await s.save(); res.json({ success: true, data: s }); }));

router.post("/showcase", auth, asyncRoute(async (req, res) => { const idea = await Idea.findById(req.body.idea); if (!idea || String(idea.owner) !== actor(req).id || !["approved", "incubation"].includes(idea.status)) throw new ApiError(403, "Only approved project owners can request showcase publication"); const showcase = await Showcase.findOneAndUpdate({ idea: req.body.idea }, { ...req.body, approved: false, published: false }, { upsert: true, new: true }); res.status(201).json({ success: true, data: showcase }); }));
router.patch("/showcase/:id", ...admin, asyncRoute(async (req, res) => { const s = await Showcase.findByIdAndUpdate(id(req), { approved: Boolean(req.body.approved), published: Boolean(req.body.published), approvedBy: actor(req).id, publishedAt: req.body.published ? new Date() : undefined }, { new: true }); if (!s) throw new ApiError(404, "Showcase item not found"); res.json({ success: true, data: s }); }));
router.get("/showcase/admin", ...admin, asyncRoute(async (_req, res) => res.json({ success: true, data: await Showcase.find().populate("idea") })));
router.get("/showcase", asyncRoute(async (_req, res) => res.json({ success: true, data: await Showcase.find({ approved: true, published: true }).populate("idea") })));
router.get("/search", auth, asyncRoute(async (req, res) => { const q = String(req.query.q || "").trim(); if (!q) throw new ApiError(400, "q is required"); const rx = new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"); const [ideas, projects, students, mentors, events] = await Promise.all([Idea.find({ $or: [{ title: rx }, { problem: rx }, { solution: rx }] }).limit(10), Project.find({ $or: [{ name: rx }, { description: rx }] }).limit(10), Student.find({ $or: [{ name: rx }, { surname: rx }, { faculty: rx }, { department: rx }, { skills: rx }, { interests: rx }], collaborationOptIn: true }).select("name surname faculty department skills interests").limit(10), MentorProfile.find({ approved: true, expertise: rx }).populate("user", "name surname").limit(10), (await import("../../models/event.model")).default.find({ status: "published", $or: [{ title: rx }, { description: rx }] }).limit(10)]); res.json({ success: true, data: { innovations: ideas, projects, students, researchers: students, mentors, events, teams: projects } }); }));
router.get("/notifications", auth, asyncRoute(async (req, res) => res.json({ success: true, data: await Notification.find({ recipient: actor(req).id }).sort({ createdAt: -1 }).limit(100) })));
router.patch("/notifications/:id/read", auth, asyncRoute(async (req, res) => { const n = await Notification.findOneAndUpdate({ _id: id(req), recipient: actor(req).id }, { readAt: new Date() }, { new: true }); if (!n) throw new ApiError(404, "Notification not found"); res.json({ success: true, data: n }); }));

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, /^(image\/|audio\/|application\/pdf|application\/msword|application\/vnd\.openxmlformats-officedocument)/.test(file.mimetype)) });
router.post("/upload", auth, upload.single("file"), asyncRoute(async (req, res) => { const file = (req as any).file; if (!file) throw new ApiError(400, "Supported image, PDF, office, or audio file required"); const resourceType = file.mimetype.startsWith("image/") ? "image" : "raw"; const result: any = await new Promise((resolve, reject) => { const stream = cloudinary.uploader.upload_stream({ folder: "innovation-hub/uploads", resource_type: resourceType }, (error, value) => error ? reject(error) : resolve(value)); stream.end(file.buffer); }); res.status(201).json({ success: true, data: { url: result.secure_url, publicId: result.public_id, resourceType, name: file.originalname, mimeType: file.mimetype, bytes: file.size } }); }));
router.post("/projects/:id/files", auth, upload.single("file"), asyncRoute(async (req, res) => { const p = await projectAccess(req); const file = (req as any).file; if (!file) throw new ApiError(400, "File required"); const result: any = await new Promise((resolve, reject) => { const stream = cloudinary.uploader.upload_stream({ folder: `innovation-hub/projects/${p._id}`, resource_type: file.mimetype.startsWith("image/") ? "image" : "raw" }, (error, value) => error ? reject(error) : resolve(value)); stream.end(file.buffer); }); const saved = await ProjectFile.create({ project: p._id, uploadedBy: actor(req).id, name: file.originalname, mimeType: file.mimetype, bytes: file.size, publicId: result.public_id, resourceType: file.mimetype.startsWith("image/") ? "image" : "raw" }); res.status(201).json({ success: true, data: saved }); }));
router.get("/projects/:id/files/:fileId", auth, asyncRoute(async (req, res) => { await projectAccess(req); const f = await ProjectFile.findOne({ _id: req.params.fileId, project: id(req) }); if (!f) throw new ApiError(404, "File not found"); res.json({ success: true, data: { ...f.toJSON(), signedUrl: f.resourceType === "raw" ? generateSignedDownloadUrl(f.publicId, 300) : cloudinary.url(f.publicId, { secure: true, sign_url: true }) } }); }));
router.get("/projects/:id/files", auth, asyncRoute(async (req, res) => { await projectAccess(req); res.json({ success: true, data: await ProjectFile.find({ project: id(req) }).sort({ createdAt: -1 }).select("name mimeType bytes uploadedBy createdAt") }); }));

export default router;
